### ISSUE TITLE
Values of simulated instances for event '8' missing.

### ISSUE THREAD

**Issue by mthlimao** [petrobras/3W#60]
The sensor values of the simulated instances for event '8' are missing. 

They don't have the original values that were available in the previous version (1.0.0), except for the P-PDG tag values, which remain the same.

**Comment by ricardoevvargas** [comment]
Hi, @mthlimao. This is a highly relevant issue. Thanks for this contribution. In a first analysis, I found that instances of other types also have this problem. We will further evaluate what happens and release a fixed version ASAP. Meanwhile, the previous version is perhaps better suited for certain experiments.

**Comment by ricardoevvargas** [comment]
This issue was resolved with the PR #67. @mthlimao, thanks for having pointed out this issue.
